// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.26.3";

// src/lib/mcp/tools/search-funds.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.99.2";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseAnon() {
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
async function loadFunds() {
  const supabase = supabaseAnon();
  const { data, error } = await supabase.from("fund_cache").select("data, fund_count, updated_at").order("updated_at", { ascending: false }).limit(1).maybeSingle();
  if (error) throw new Error(error.message);
  const funds = data?.data ?? [];
  return {
    funds,
    updatedAt: data?.updated_at ?? null,
    fundCount: data?.fund_count ?? null
  };
}
function parseNum(val) {
  if (val === null || val === void 0 || val === "-" || val === "") return NaN;
  return parseFloat(String(val).replace(",", "."));
}

// src/lib/mcp/tools/search-funds.ts
var SORT_KEYS = [
  "Avkastning_YTD_%",
  "Avkastning_snitt_1\xE5r_%",
  "Avkastning_snitt_3\xE5r_%",
  "Avkastning_snitt_5\xE5r_%",
  "Avkastning_snitt_10\xE5r_%",
  "Volatilitet_1\xE5r",
  "Volatilitet_3\xE5r",
  "Volatilitet_5\xE5r",
  "Volatilitet_10\xE5r",
  "Sharpe_1\xE5r",
  "Sharpe_3\xE5r",
  "Sharpe_5\xE5r",
  "Sharpe_10\xE5r"
];
var search_funds_default = defineTool({
  name: "search_funds",
  title: "S\xF8k i fond",
  description: "S\xF8k og filtrer norske fond p\xE5 navn, fondstype, fondsgruppe, forvaltningsselskap og minimum tegningsbel\xF8p. Sorterer p\xE5 avkastning, volatilitet eller Sharpe-ratio.",
  inputSchema: {
    query: z.string().trim().optional().describe("Friteksts\xF8k i fondsnavn."),
    fondstype: z.string().trim().optional().describe("Eksakt fondstype, f.eks. 'Aksjefond'."),
    fondsgruppe: z.string().trim().optional().describe("Eksakt fondsgruppe."),
    forvaltningsselskap: z.string().trim().optional().describe("Eksakt forvaltningsselskap."),
    maxMinTegningsbelop: z.number().positive().optional().describe("Ta kun med fond med minimum tegningsbel\xF8p under denne verdien (NOK)."),
    sortBy: z.enum(SORT_KEYS).optional().describe("Kolonne \xE5 sortere synkende p\xE5 (h\xF8yest f\xF8rst)."),
    limit: z.number().int().min(1).max(200).default(20).describe("Maks antall fond som returneres.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, fondstype, fondsgruppe, forvaltningsselskap, maxMinTegningsbelop, sortBy, limit }) => {
    const { funds, updatedAt } = await loadFunds();
    const q = query?.toLowerCase();
    let result = funds.filter((f) => {
      if (q && !String(f.Fondsnavn ?? "").toLowerCase().includes(q)) return false;
      if (fondstype && f.Fondstype !== fondstype) return false;
      if (fondsgruppe && f.Fondsgruppe !== fondsgruppe) return false;
      if (forvaltningsselskap && f.Forvaltningsselskap !== forvaltningsselskap) return false;
      if (maxMinTegningsbelop !== void 0) {
        const amt = parseNum(f["Min_tegningsbel\xF8p"]);
        if (!isNaN(amt) && amt >= maxMinTegningsbelop) return false;
      }
      return true;
    });
    if (sortBy) {
      result = [...result].sort((a, b) => {
        const na = parseNum(a[sortBy]);
        const nb = parseNum(b[sortBy]);
        if (isNaN(na) && isNaN(nb)) return 0;
        if (isNaN(na)) return 1;
        if (isNaN(nb)) return -1;
        return nb - na;
      });
    }
    const matched = result.length;
    const rows = result.slice(0, limit);
    return {
      content: [
        {
          type: "text",
          text: `${matched} fond matchet (viser ${rows.length}). Data oppdatert: ${updatedAt ?? "ukjent"}.

${JSON.stringify(rows, null, 2)}`
        }
      ],
      structuredContent: { matched, returned: rows.length, updatedAt, funds: rows }
    };
  }
});

// src/lib/mcp/tools/get-fund.ts
import { defineTool as defineTool2, ToolError } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z as z2 } from "npm:zod@^3.25.76";
var get_fund_default = defineTool2({
  name: "get_fund",
  title: "Hent fond",
  description: "Hent alle n\xF8kkeltall (avkastning, volatilitet, Sharpe, min. tegningsbel\xF8p) for ett fond ved navn.",
  inputSchema: {
    fondsnavn: z2.string().trim().min(1).describe("Fondsnavn, helt eller delvis.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ fondsnavn }) => {
    const { funds, updatedAt } = await loadFunds();
    const q = fondsnavn.toLowerCase();
    const exact = funds.find((f) => String(f.Fondsnavn ?? "").toLowerCase() === q);
    const fund = exact ?? funds.find((f) => String(f.Fondsnavn ?? "").toLowerCase().includes(q));
    if (!fund) throw new ToolError(`Fant ingen fond som matcher "${fondsnavn}".`);
    return {
      content: [{ type: "text", text: JSON.stringify(fund, null, 2) }],
      structuredContent: { fund, updatedAt }
    };
  }
});

// src/lib/mcp/tools/list-filter-options.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z as z3 } from "npm:zod@^3.25.76";
var FIELDS = ["Fondstype", "Fondsgruppe", "Forvaltningsselskap"];
var list_filter_options_default = defineTool3({
  name: "list_filter_options",
  title: "List filtervalg",
  description: "List tilgjengelige verdier for fondstype, fondsgruppe eller forvaltningsselskap, samt n\xE5r fondsdataen sist ble oppdatert.",
  inputSchema: {
    field: z3.enum(FIELDS).describe("Feltet du vil ha unike verdier for.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ field }) => {
    const { funds, updatedAt, fundCount } = await loadFunds();
    const values = [...new Set(funds.map((f) => f[field]))].filter((v) => v && v !== "-").sort((a, b) => a.localeCompare(b, "nb"));
    return {
      content: [
        {
          type: "text",
          text: `${values.length} verdier for ${field} (${fundCount ?? funds.length} fond, oppdatert ${updatedAt ?? "ukjent"}):
${values.join("\n")}`
        }
      ],
      structuredContent: { field, values, updatedAt, fundCount }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "godefond",
  title: "GodeFond",
  version: "0.1.0",
  instructions: "Verkt\xF8y for GodeFond: offentlige n\xF8kkeltall for norske fond (avkastning, volatilitet, Sharpe-ratio, minimum tegningsbel\xF8p) fra VFF. Bruk `list_filter_options` for \xE5 finne gyldige fondstyper, fondsgrupper og forvaltningsselskaper, `search_funds` for \xE5 filtrere og rangere fond, og `get_fund` for detaljer om ett fond.",
  tools: [search_funds_default, get_fund_default, list_filter_options_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.3/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
